"""empty message

Revision ID: 971abb99e2bf
Revises: 4da95036b972
Create Date: 2021-04-27 12:50:19.600642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971abb99e2bf'
down_revision = '4da95036b972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('address', sa.String(length=120), nullable=False))
    op.add_column('Venue', sa.Column('city', sa.String(length=120), nullable=False))
    op.add_column('Venue', sa.Column('facebook_link', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('image_link', sa.String(length=500), nullable=True))
    op.add_column('Venue', sa.Column('looking_for_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('phone', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('Venue', sa.Column('state', sa.String(length=120), nullable=False))
    op.add_column('Venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website_link')
    op.drop_column('Venue', 'state')
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'phone')
    op.drop_column('Venue', 'looking_for_talent')
    op.drop_column('Venue', 'image_link')
    op.drop_column('Venue', 'facebook_link')
    op.drop_column('Venue', 'city')
    op.drop_column('Venue', 'address')
    # ### end Alembic commands ###
